## Data Understanding

In [3]:
import pandas as pd
from ydata_profiling import ProfileReport

In [4]:
df = pd.read_csv("../Data/Metro_Interstate_Traffic_Volume_modified.csv")

## ydata-profiling

In [5]:
profile = ProfileReport(
    df,
    title="Metro_Interstate_Traffic_Volume_modified Dataset Profile",
    explorative=True
)

In [6]:
profile.to_file("Metro_Interstate_Traffic_Volume_modified_profile_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 13/13 [00:19<00:00,  1.53s/it]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
df.shape

(48204, 13)

In [8]:
df.columns

Index(['date_time', 'temp', 'rain_1h', 'snow_1h', 'clouds_all', 'fog_mm',
       'wind_speed_ms', 'flood_mm', 'holiday', 'weather_main',
       'weather_description', 'day_type', 'traffic_volume'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48204 entries, 0 to 48203
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date_time            48204 non-null  object
 1   temp                 45794 non-null  float64
 2   rain_1h              45792 non-null  float64
 3   snow_1h              45793 non-null  float64
 4   clouds_all           45794 non-null  float64
 5   fog_mm               48204 non-null  float64
 6   wind_speed_ms        48204 non-null  float64
 7   flood_mm             48202 non-null  float64
 8   holiday              61 non-null     object
 9   weather_main         48204 non-null  object
 10  weather_description  48204 non-null  object
 11  day_type             48204 non-null  object
 12  traffic_volume       45794 non-null  float64
dtypes: float64(8), object(5)
memory usage: 4.8+ MB

In [10]:
df.describe()

,temp,rain_1h,snow_1h,clouds_all,fog_mm,wind_speed_ms,flood_mm,traffic_volume
count,45794.000000,45792.000000,45793.000000,45794.000000,48204.000000,48204.000000,48202.000000,45794.000000
mean,281.219070,0.345503,0.000230,49.406931,8.568209,5.396802,0.785051,3261.366991
std,13.378092,45.953150,0.008367,39.021861,42.113011,3.548947,8.152681,1987.139170
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000
25%,272.180000,0.000000,0.000000,1.000000,0.000000,2.820000,0.000000,1195.000000
50%,282.480000,0.000000,0.000000,64.000000,0.000000,5.050000,0.000000,3380.000000
75%,291.830000,0.000000,0.000000,90.000000,0.000000,7.040000,0.000000,4936.000000
max,310.070000,9831.300000,0.510000,100.000000,499.260000,24.980000,407.930000,7280.000000

In [11]:
df.describe(include="object")

            date_time    holiday weather_main weather_description day_type
count           48204         61        48204               48204    48204
unique          40575         11           11                  38        2
top     5/19/13 10:00  Labor Day       Clouds        sky is clear  Weekday
freq                6          7        15164               11665    34501

In [12]:
df.head()

,date_time,temp,rain_1h,snow_1h,clouds_all,fog_mm,wind_speed_ms,flood_mm,holiday,weather_main,weather_description,day_type,traffic_volume
0,10/2/12 9:00,288.28,0.0,0.0,40.0,0.0,2.30,0.0,NaN,Clouds,scattered clouds,Weekday,5545.0
1,10/2/12 10:00,289.36,0.0,0.0,75.0,0.0,7.45,0.0,NaN,Clouds,broken clouds,Weekday,4516.0
2,10/2/12 11:00,289.58,0.0,0.0,90.0,0.0,5.68,0.0,NaN,Clouds,overcast clouds,Weekday,NaN
3,10/2/12 12:00,290.13,0.0,0.0,90.0,0.0,1.93,0.0,NaN,Clouds,overcast clouds,Weekday,5026.0
4,10/2/12 13:00,NaN,0.0,0.0,75.0,0.0,3.56,0.0,NaN,Clouds,broken clouds,Weekday,4918.0

In [13]:
df.tail()

,date_time,temp,rain_1h,snow_1h,clouds_all,fog_mm,wind_speed_ms,flood_mm,holiday,weather_main,weather_description,day_type,traffic_volume
48199,9/30/18 19:00,283.45,0.0,0.0,NaN,0.0,6.10,0.0,NaN,Clouds,broken clouds,Weekend,3543.0
48200,9/30/18 20:00,282.76,0.0,0.0,NaN,0.0,1.83,0.0,NaN,Clouds,overcast clouds,Weekend,2781.0
48201,9/30/18 21:00,282.73,0.0,0.0,90.0,0.0,22.42,0.0,NaN,Thunderstorm,proximity thunderstorm,Weekend,2159.0
48202,9/30/18 22:00,282.09,NaN,0.0,90.0,0.0,7.68,0.0,NaN,Clouds,overcast clouds,Weekend,1450.0
48203,9/30/18 23:00,282.12,0.0,0.0,90.0,0.0,1.37,0.0,NaN,Clouds,overcast clouds,Weekend,954.0

In [14]:
df["traffic_volume"].value_counts()

traffic_volume
353.0     50
356.0     44
351.0     43
340.0     43
373.0     41
          ..
1594.0     1
1061.0     1
6935.0     1
6977.0     1
6918.0     1
Name: count, Length: 6684, dtype: int64

In [15]:
df["traffic_volume"].value_counts(normalize=True) * 100

traffic_volume
353.0     0.109185
356.0     0.096082
351.0     0.093899
340.0     0.093899
373.0     0.089531
            ...
1594.0    0.002184
1061.0    0.002184
6935.0    0.002184
6977.0    0.002184
6918.0    0.002184
Name: proportion, Length: 6684, dtype: float64